name: CrudJS Release
on:
    push:
        tags:
            - 'v*'
jobs:
    release:
        name: Release Job
        runs-on: ubuntu-latest
        steps:
            - uses: technote-space/release-github-actions@v4
              with:
                  PACKAGE_MANAGER: npm
                  BUILD_COMMAND_TARGET: build:dist
                  CLEAN_TARGETS: node_modules, .github, *.lock, *-lock.json, *-error.log
